/**
 * Bundle the STATIC documentation resources into the package so `npx typeflux-mcp` is self-
 * contained (#326 Phase 0). Copies the design-listed docs and distills each example project into a
 * single reviewable blob, writing them under src/generated/ (gitignored, shipped via the `files`
 * allowlist). Regenerated by `prebuild` and `pretest`.
 *
 * Source of truth is the monorepo (docs/, docs/typescript/, packages/python/examples/,
 * packages/typescript/temporal-yaml/examples/). OUTSIDE the monorepo (a
 * published install where those trees are absent) this is a no-op — the already-bundled
 * src/generated/ content is authoritative.
 */

import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(HERE, "..");
const REPO_ROOT = resolve(PKG_ROOT, "../..");
const DOCS_SRC = join(REPO_ROOT, "docs");
const TS_DOCS_SRC = join(REPO_ROOT, "docs/typescript");
const EXAMPLES_SRC = join(REPO_ROOT, "packages/python/examples");
const TS_EXAMPLES_SRC = join(REPO_ROOT, "packages/typescript/temporal-yaml/examples");
const OUT = join(PKG_ROOT, "src/generated");

/** The docs surfaced as `typeflux://docs/{slug}` (design §5). */
const DOC_SLUGS = [
  "concepts",
  "yaml",
  "code-defined-workflows",
  "control-plane",
  "control-plane-auth",
  "provider-portability",
  "observability",
];

/**
 * The TS-edition mirror, surfaced under its own namespace — `typeflux://docs/typescript/{slug}`
 * (#862) — so it can never collide with the language-neutral pages above. `README.md` is a
 * directory index of relative links and is deliberately not bundled.
 */
const TS_DOC_SLUGS = [
  "tutorial",
  "concepts",
  "yaml",
  "code-defined-workflows",
  "observability",
  "privacy",
  "provider-portability",
];

/** Directories under packages/python/examples that are NOT example projects. */
const NON_EXAMPLES = new Set(["environments", "policies", "__pycache__"]);

/**
 * Examples excluded from the published authoring surface (they are not part of the
 * public tree — see docs/open-source/public-tree-manifest.txt). Never bundled.
 */
export const EXCLUDED_EXAMPLES = new Set(["mlr_claim_substantiation"]);

/** The illustrative files of an example, in a stable order (YAML first, then the code shape). */
const EXAMPLE_FILE_ORDER = [
  "typeflux.project.yaml",
  "workflow.yaml",
  "schemas.py",
  "activities.py",
  "workflow.py",
];

function readIfPresent(path) {
  return existsSync(path) ? readFileSync(path, "utf8") : undefined;
}

/** Every *.yaml plus the primary code files of an example dir, concatenated with headers. */
function distillExample(name, dir) {
  const parts = [];
  const seen = new Set();
  const push = (rel, abs) => {
    const text = readIfPresent(abs);
    if (text === undefined || seen.has(rel)) return;
    seen.add(rel);
    const lang = rel.endsWith(".py") ? "python" : "yaml";
    parts.push(`### ${rel}\n\n\`\`\`${lang}\n${text.trimEnd()}\n\`\`\``);
  };
  // Ordered primary files first.
  for (const file of EXAMPLE_FILE_ORDER) push(file, join(dir, file));
  // Then any remaining top-level YAML (multi-workflow examples).
  for (const file of readdirSync(dir).sort()) {
    if (file.endsWith(".yaml")) push(file, join(dir, file));
  }
  if (parts.length === 0) return undefined;
  return `# Typeflux example: ${name}\n\nDistilled from packages/python/examples/${name} (#326).\n\n${parts.join("\n\n")}\n`;
}

/**
 * The TS-edition file order (#863): YAML first, then the code shape in reading order. `fakes.ts`
 * and `sample-*.ts` are demo fixtures, not the shape an author copies, so they stay out.
 */
const TS_EXAMPLE_FILE_ORDER = ["typeflux.yaml", "schemas.ts", "activities.ts", "hooks.ts", "main.ts"];

/** Distill a TS example dir: ordered code files, remaining top-level YAML, then `policies/*.yaml`. */
function distillTsExample(name, dir) {
  const parts = [];
  const seen = new Set();
  const push = (rel, abs) => {
    const text = readIfPresent(abs);
    if (text === undefined || seen.has(rel)) return;
    seen.add(rel);
    const lang = rel.endsWith(".ts") ? "typescript" : "yaml";
    parts.push(`### ${rel}\n\n\`\`\`${lang}\n${text.trimEnd()}\n\`\`\``);
  };
  for (const file of TS_EXAMPLE_FILE_ORDER) push(file, join(dir, file));
  for (const file of readdirSync(dir).sort()) {
    if (file.endsWith(".yaml")) push(file, join(dir, file));
  }
  // Governance examples keep their policies next to the spec — a policy-governed example
  // without its policy YAML is hollow.
  const policiesDir = join(dir, "policies");
  if (existsSync(policiesDir)) {
    for (const file of readdirSync(policiesDir).sort()) {
      if (file.endsWith(".yaml")) push(`policies/${file}`, join(policiesDir, file));
    }
  }
  if (parts.length === 0) return undefined;
  return `# Typeflux example (TypeScript edition): ${name}\n\nDistilled from packages/typescript/temporal-yaml/examples/${name} (#863).\n\n${parts.join("\n\n")}\n`;
}

function listExampleDirsIn(root) {
  if (!existsSync(root)) return [];
  return readdirSync(root)
    .filter((name) => !NON_EXAMPLES.has(name) && !EXCLUDED_EXAMPLES.has(name))
    .filter((name) => !name.startsWith("__") && !name.startsWith("."))
    .filter((name) => {
      try {
        return statSync(join(root, name)).isDirectory();
      } catch {
        return false;
      }
    })
    .sort();
}

async function main() {
  const SOURCES = [DOCS_SRC, TS_DOCS_SRC, EXAMPLES_SRC, TS_EXAMPLES_SRC];
  if (!SOURCES.some((dir) => existsSync(dir))) {
    process.stderr.write(
      "generate-assets: monorepo docs/examples not found; keeping bundled src/generated/*\n",
    );
    return;
  }

  await rm(OUT, { recursive: true, force: true });
  await mkdir(join(OUT, "docs", "typescript"), { recursive: true });
  await mkdir(join(OUT, "examples", "typescript"), { recursive: true });

  // Docs — one loop per edition row, so a future edition is a table entry, not a new loop.
  const copyDocs = async ({ slugs, srcDir, outDir, label }) => {
    const copied = [];
    for (const slug of slugs) {
      const text = readIfPresent(join(srcDir, `${slug}.md`));
      if (text === undefined) {
        process.stderr.write(`generate-assets: WARNING doc not found: ${label}${slug}.md\n`);
        continue;
      }
      await writeFile(join(outDir, `${slug}.md`), text, "utf8");
      copied.push(slug);
    }
    return copied;
  };
  const docs = await copyDocs({ slugs: DOC_SLUGS, srcDir: DOCS_SRC, outDir: join(OUT, "docs"), label: "" });
  // TypeScript-edition docs (#862), under their own namespace directory.
  const docsTypescript = await copyDocs({
    slugs: TS_DOC_SLUGS,
    srcDir: TS_DOCS_SRC,
    outDir: join(OUT, "docs", "typescript"),
    label: "typescript/",
  });

  // Examples.
  const examples = [];
  for (const name of listExampleDirsIn(EXAMPLES_SRC)) {
    const blob = distillExample(name, join(EXAMPLES_SRC, name));
    if (blob === undefined) continue;
    await writeFile(join(OUT, "examples", `${name}.md`), blob, "utf8");
    examples.push(name);
  }

  // TypeScript-edition examples (#863).
  const examplesTypescript = [];
  for (const name of listExampleDirsIn(TS_EXAMPLES_SRC)) {
    const blob = distillTsExample(name, join(TS_EXAMPLES_SRC, name));
    if (blob === undefined) continue;
    await writeFile(join(OUT, "examples", "typescript", `${name}.md`), blob, "utf8");
    examplesTypescript.push(name);
  }

  await writeFile(
    join(OUT, "index.json"),
    `${JSON.stringify({ docs, docsTypescript, examples, examplesTypescript }, null, 2)}\n`,
    "utf8",
  );
  process.stderr.write(
    `generate-assets: wrote ${docs.length} docs (+${docsTypescript.length} TS), ` +
      `${examples.length} examples (+${examplesTypescript.length} TS) to src/generated/\n`,
  );
}

// Run only when executed directly — verify-pack.mjs imports EXCLUDED_EXAMPLES
// from this module and must not trigger an unawaited regeneration underneath
// its own scan.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    process.stderr.write(`generate-assets failed: ${error instanceof Error ? error.stack : String(error)}\n`);
    process.exit(1);
  });
}
