/**
 * Generate the two `typeflux://schema/*` JSON Schemas from the AUTHORITATIVE zod specs
 * (`@typeflux/temporal-yaml`) via Zod 4's `z.toJSONSchema`, and commit them as static JSON
 * under src/schema/. #326 Phase 0.
 *
 * WHY generated (not hand-authored): the zod specs in packages/typescript/temporal-yaml are
 * the strict single source of truth for the workflow YAML and the project manifest. Deriving
 * the JSON Schema from them keeps the agent-facing schema faithful and fresh, with no Python
 * invocation (pure Node) and no hand-maintained second copy that silently drifts.
 *
 * FRESHNESS CAVEAT: the output is committed and SHIPPED as static JSON so an `npx typeflux-mcp`
 * install needs no monorepo checkout. It is regenerated by the `prebuild` hook from the local
 * temporal-yaml dist; a test (`test/schema.test.ts`) reruns this generation and diffs it against
 * the committed files, so a spec change that skips regeneration fails CI rather than shipping a
 * stale schema. When consumed outside the monorepo (temporal-yaml dist absent) this script is a
 * no-op — the committed JSON is authoritative there.
 *
 * `io: "input"` — the schema an author WRITES (before defaults/coercion), which is what an agent
 * validates a hand-written YAML file against. `unrepresentable: "any"` — a handful of spec nodes
 * (env-interpolation string/bool unions, preprocess guards) have no JSON-Schema form; emit `{}`
 * (accept-any) for those rather than throwing, so the rest of the schema stays precise.
 */

import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(HERE, "../src/schema");
const YAML_DIST = resolve(HERE, "../../../packages/typescript/temporal-yaml/dist");

async function main() {
  if (!existsSync(resolve(YAML_DIST, "index.js"))) {
    // Outside the monorepo (e.g. a published install): the committed JSON is authoritative.
    process.stderr.write(
      "generate-schemas: @typeflux/temporal-yaml dist not found; keeping committed src/schema/*.json\n",
    );
    return;
  }

  const { z } = await import("zod");
  const { typefluxYamlSpec } = await import(pathToFileURL(resolve(YAML_DIST, "index.js")).href);
  const { typefluxProjectSpec } = await import(
    pathToFileURL(resolve(YAML_DIST, "project-spec.js")).href
  );

  const opts = { unrepresentable: "any", io: "input" };
  const targets = [
    {
      file: "typeflux-yaml.schema.json",
      title: "Typeflux workflow YAML (typeflux.yaml)",
      schema: typefluxYamlSpec,
    },
    {
      file: "project.schema.json",
      title: "Typeflux project manifest (typeflux.project.yaml)",
      schema: typefluxProjectSpec,
    },
  ];

  await mkdir(OUT_DIR, { recursive: true });
  for (const { file, title, schema } of targets) {
    const jsonSchema = z.toJSONSchema(schema, opts);
    const annotated = {
      $schema: "https://json-schema.org/draft/2020-12/schema",
      title,
      "x-typeflux-generated":
        "Generated from packages/typescript/temporal-yaml zod specs via z.toJSONSchema (#326). Do not hand-edit; run `npm run generate:schemas`.",
      ...jsonSchema,
    };
    await writeFile(resolve(OUT_DIR, file), `${JSON.stringify(annotated, null, 2)}\n`, "utf8");
    process.stderr.write(`generate-schemas: wrote src/schema/${file}\n`);
  }
}

main().catch((error) => {
  process.stderr.write(`generate-schemas failed: ${error instanceof Error ? error.stack : String(error)}\n`);
  process.exit(1);
});
